CREATE TABLE IF NOT EXISTS db_sizes (
    DATABASE_NAME VARCHAR,
    FILENAME VARCHAR,
    TYPE_DESC VARCHAR,
    CURRENTSIZEMB VARCHAR,
    FREESPACEINMB VARCHAR,
    MAXSIZE BIGINT,
    EXTRACT_TS TIMESTAMP
);
