CREATE TABLE IF NOT EXISTS db_sizes (
    DATABASE_NAME VARCHAR,
    FILENAME VARCHAR,
    TYPE_DESC VARCHAR,
    CURRENTSIZEMB DOUBLE,
    FREESPACEINMB DOUBLE,
    MAXSIZE BIGINT,
    EXTRACT_TS TIMESTAMP
);
