CREATE TABLE IF NOT EXISTS indexed_views (
    DATABASE_NAME VARCHAR,
    INDEXED_VIEW_NAME VARCHAR,
    SCHEMA_NAME VARCHAR,
    INDEX_NAME VARCHAR,
    INDEX_TYPE VARCHAR,
    INDEX_ID INTEGER,
    EXTRACT_TS TIMESTAMP
);
