name: mssql_assessment
version: "1.0"
extract_folder: "/tmp/data/mssql_assessment"
steps:
  - name: activity_extract
    type: python
    extract_source: src/databricks/labs/lakebridge/resources/assessments/mssql/activity_extract.py
    mode: overwrite
    frequency: once
    flag: active
    dependencies:
      - pandas
      - duckdb
      - databricks-sdk
      - databricks-labs-blueprint[yaml]>=0.10.1
      - sqlalchemy
      - azure-synapse-artifacts
      - azure-mgmt-sql
      - azure-identity
      - azure-monitor-query==1.3.0b1
      - pyodbc
  - name: info_extract
    type: python
    extract_source: src/databricks/labs/lakebridge/resources/assessments/mssql/info_extract.py
    mode: overwrite
    frequency: once
    flag: active
    dependencies:
      - pandas
      - duckdb
      - databricks-sdk
      - databricks-labs-blueprint[yaml]>=0.10.1
      - sqlalchemy
      - azure-synapse-artifacts
      - azure-mgmt-sql
      - azure-identity
      - azure-monitor-query==1.3.0b1
      - pyodbc
