CREATE TABLE IF NOT EXISTS proc_stats (
    DATABASE_ID INTEGER,
    DB_NAME VARCHAR,
    OBJECT_ID INTEGER,
    OBJECT_NAME VARCHAR,
    TYPE VARCHAR,
    LAST_EXECUTION_TIME TIMESTAMP,
    EXECUTION_COUNT BIGINT,
    TOTAL_WORKER_TIME BIGINT,
    TOTAL_ELAPSED_TIME BIGINT,
    EXTRACT_TS TIMESTAMP
);
