CREATE TABLE IF NOT EXISTS query_stats (
    DBID SMALLINT,
    CREATION_TIME TIMESTAMP,
    LAST_EXECUTION_TIME TIMESTAMP,
    EXECUTION_COUNT BIGINT,
    TOTAL_WORKER_TIME BIGINT,
    TOTAL_ELAPSED_TIME BIGINT,
    TOTAL_ROWS BIGINT,
    COMMAND VARCHAR,
    COMMAND_TYPE VARCHAR,
    EXTRACT_TS TIMESTAMP
);
