CREATE TABLE IF NOT EXISTS sessions (
    SESSION_ID SMALLINT,
    LOGIN_TIME TIMESTAMP,
    PROGRAM_NAME VARCHAR,
    CLIENT_INTERFACE_NAME VARCHAR,
    LOGIN_NAME VARCHAR,
    STATUS VARCHAR,
    CPU_TIME INTEGER,
    MEMORY_USAGE INTEGER,
    TOTAL_SCHEDULED_TIME BIGINT,
    TOTAL_ELAPSED_TIME BIGINT,
    LAST_REQUEST_START_TIME TIMESTAMP,
    LAST_REQUEST_END_TIME TIMESTAMP,
    IS_USER_PROCESS BOOLEAN,
    ROW_COUNT BIGINT,
    DATABASE_ID SMALLINT,
    DB_NAME VARCHAR,
    EXTRACT_TS TIMESTAMP
);
