CREATE TABLE IF NOT EXISTS table_sizes (
    TABLENAME VARCHAR,
    ROWCOUNT BIGINT,
    RESERVEDMB BIGINT,
    USEDMB BIGINT,
    UNUSEDMB BIGINT,
    DATAMB BIGINT,
    INDEXMB BIGINT,
    EXTRACT_TS TIMESTAMP
);
