CREATE TABLE IF NOT EXISTS views (
    DATABASE_NAME VARCHAR,
    TABLE_CATALOG VARCHAR,
    TABLE_SCHEMA VARCHAR,
    TABLE_NAME VARCHAR,
    CHECK_OPTION VARCHAR,
    IS_UPDATABLE VARCHAR,
    VIEW_DEFINITION VARCHAR
);
