name: synapse_assessment
version: "1.0"
steps:
  - name: workspace_info
    type: python
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse/workspace_extract.py
    mode: overwrite
    frequency: once
    flag: active
  - name: monitoring_metrics
    type: python
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse/monitoring_metrics_extract.py
    mode: overwrite
    frequency: once
    flag: active
  - name: dedicated_sqlpool_extract
    type: python
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse/dedicated_sqlpool_extract.py
    mode: overwrite
    frequency: once
    flag: active
  - name: serverless_sqlpool_extract
    type: python
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse/serverless_sqlpool_extract.py
    mode: overwrite
    frequency: once
    flag: active
