-- Account Information and Basic Metadata
-- Extracts basic account-level info and object counts

SELECT
    CURRENT_ACCOUNT() as ACCOUNT_NAME,
    CURRENT_REGION() as REGION,
    CURRENT_VERSION() as SNOWFLAKE_VERSION,
    (SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASES WHERE DELETED IS NULL)::VARCHAR as DATABASE_COUNT,
    (SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.USERS WHERE DELETED_ON IS NULL)::VARCHAR as USER_COUNT,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP;
