CREATE TABLE automatic_clustering (
    DATABASE_NAME VARCHAR,
    SCHEMA_NAME VARCHAR,
    TABLE_NAME VARCHAR,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    CREDITS_USED DOUBLE,
    NUM_BYTES_RECLUSTERED DOUBLE,
    NUM_ROWS_RECLUSTERED DOUBLE,
    EXTRACT_TIMESTAMP TIMESTAMP
);
