CREATE TABLE database_objects (
    DATABASE_NAME VARCHAR,
    DATABASE_OWNER VARCHAR,
    IS_TRANSIENT VARCHAR,
    CREATED TIMESTAMP,
    LAST_ALTERED TIMESTAMP,
    DELETED TIMESTAMP,
    COMMENT VARCHAR,
    OBJECT_TYPE VARCHAR,
    EXTRACT_TIMESTAMP TIMESTAMP
);
