CREATE TABLE materialized_view_refresh (
    DATABASE_NAME VARCHAR,
    SCHEMA_NAME VARCHAR,
    TABLE_NAME VARCHAR,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    CREDITS_USED DOUBLE,
    EXTRACT_TIMESTAMP TIMESTAMP
);
