CREATE TABLE pipe_usage (
    PIPE_NAME VARCHAR,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    CREDITS_USED DOUBLE,
    BYTES_INSERTED DOUBLE,
    FILES_INSERTED BIGINT,
    EXTRACT_TIMESTAMP TIMESTAMP
);
