CREATE TABLE query_samples (
    QUERY_ID VARCHAR,
    QUERY_TEXT VARCHAR,
    QUERY_TYPE VARCHAR,
    USER_NAME VARCHAR,
    WAREHOUSE_NAME VARCHAR,
    WAREHOUSE_SIZE VARCHAR,
    START_TIME TIMESTAMP,
    TOTAL_ELAPSED_TIME DOUBLE,
    EXTRACT_TIMESTAMP TIMESTAMP
);
