CREATE TABLE rate_sheet (
    REGION VARCHAR,
    TIER VARCHAR,
    RATING_TYPE VARCHAR,
    SERVICE_TYPE VARCHAR,
    CURRENCY VARCHAR,
    AVG_EFFECTIVE_RATE DOUBLE,
    RATE_DAYS BIGINT,
    PERIOD_START DATE,
    PERIOD_END DATE,
    EXTRACT_TIMESTAMP TIMESTAMP
);
