CREATE TABLE storage_usage (
    DATABASE_NAME VARCHAR,
    USAGE_DATE TIMESTAMP,
    AVERAGE_DATABASE_BYTES DOUBLE,
    AVERAGE_FAILSAFE_BYTES DOUBLE,
    STORAGE_GB DOUBLE,
    FAILSAFE_GB DOUBLE,
    USAGE_MONTH BIGINT,
    USAGE_YEAR BIGINT,
    EXTRACT_TIMESTAMP TIMESTAMP
);
