CREATE TABLE warehouse_usage (
    WAREHOUSE_NAME VARCHAR,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    CREDITS_USED DOUBLE,
    CREDITS_USED_COMPUTE DOUBLE,
    CREDITS_USED_CLOUD_SERVICES DOUBLE,
    USAGE_DATE TIMESTAMP,
    USAGE_HOUR BIGINT,
    DAY_OF_WEEK BIGINT,
    EXTRACT_TIMESTAMP TIMESTAMP
);
