-- Warehouse Usage and Performance Analysis
-- Extract warehouse utilization metrics from metering history

SELECT
    WAREHOUSE_NAME,
    START_TIME,
    END_TIME,
    CREDITS_USED,
    CREDITS_USED_COMPUTE,
    CREDITS_USED_CLOUD_SERVICES,
    DATE(START_TIME) as USAGE_DATE,
    HOUR(START_TIME) as USAGE_HOUR,
    EXTRACT(dayofweek FROM START_TIME) as DAY_OF_WEEK,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -90, CURRENT_TIMESTAMP())
    AND CREDITS_USED > 0
ORDER BY START_TIME DESC;
