CREATE TABLE columns (
    table_catalog VARCHAR,
    table_schema VARCHAR,
    table_name VARCHAR,
    column_name VARCHAR,
    ordinal_position BIGINT,
    column_default VARCHAR,
    is_nullable VARCHAR,
    data_type VARCHAR,
    character_maximum_length BIGINT,
    character_octet_length BIGINT,
    numeric_precision BIGINT,
    numeric_precision_radix BIGINT,
    numeric_scale BIGINT,
    datetime_precision BIGINT,
    character_set_catalog VARCHAR,
    character_set_schema VARCHAR,
    character_set_name VARCHAR,
    collation_catalog VARCHAR,
    collation_schema VARCHAR,
    collation_name VARCHAR,
    domain_catalog VARCHAR,
    domain_schema VARCHAR,
    domain_name VARCHAR
);
