CREATE TABLE routines (
    created TIMESTAMP,
    data_type VARCHAR,
    is_deterministic VARCHAR,
    is_implicitly_invocable VARCHAR,
    is_null_call VARCHAR,
    is_user_defined_cast VARCHAR,
    last_altered TIMESTAMP,
    max_dynamic_result_sets VARCHAR,
    numeric_precision BIGINT,
    numeric_precision_radix BIGINT,
    numeric_scale BIGINT,
    routine_body VARCHAR,
    routine_catalog VARCHAR,
    ROUTINE_DEFINITION VARCHAR,
    routine_name VARCHAR,
    routine_schema VARCHAR,
    routine_type VARCHAR,
    schema_level_routine VARCHAR,
    specific_catalog VARCHAR,
    specific_name VARCHAR,
    specific_schema VARCHAR,
    sql_data_access VARCHAR
);
