name: synapse_dedicated_sqlpool_assessment
version: "1.0"
extract_folder: "/tmp/data/synapse_dedicated_sqlpool_assessment"
steps:
  - name: columns
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse_dedicated_sqlpool/columns.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: routines
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse_dedicated_sqlpool/routines.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: tables
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse_dedicated_sqlpool/tables.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: views
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse_dedicated_sqlpool/views.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: sessions
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse_dedicated_sqlpool/sessions.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: requests
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse_dedicated_sqlpool/requests.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: storage_info
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse_dedicated_sqlpool/storage_info.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: databases
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/synapse_dedicated_sqlpool/databases.sql
    mode: overwrite
    frequency: once
    flag: active
