CREATE TABLE td_pdcr_info_agg_extract (
    LogType VARCHAR,
    LogDate DATE,
    DOW VARCHAR,
    HR BIGINT,
    LogHour_TS TIMESTAMP,
    Organization VARCHAR,
    Department VARCHAR,
    WdName VARCHAR,
    AcctString VARCHAR,
    Username VARCHAR,
    userId VARCHAR,
    AppId VARCHAR,
    QueryType VARCHAR,
    QryCNT BIGINT,
    SumCPU DOUBLE,
    AvgCPU DOUBLE,
    MaxCPU DOUBLE,
    SumIO DOUBLE,
    AvgIO DOUBLE,
    MaxIO DOUBLE,
    MaxTDWMDelayTime DOUBLE,
    SumTDWMDelayTime DOUBLE,
    AvgRespSecs DOUBLE,
    MaxRespSecs DOUBLE
);
