/**
 * Multi-database variant: retrieves routine (stored procedure / function) metadata across every
 * accessible, online user database by dynamically UNION-ing INFORMATION_SCHEMA.ROUTINES from each
 * database, tagging each row with its source `database_name`. ROUTINE_DEFINITION is redacted, matching
 * the single-database extract. The WHERE 1 = 0 anchor guarantees a single, correctly-typed result set.
 * Requires three-part naming (on-prem SQL Server / Azure SQL Managed Instance only).
 */
SET NOCOUNT ON;

DECLARE @cols NVARCHAR(MAX) =
    N'CREATED, DATA_TYPE COLLATE DATABASE_DEFAULT AS DATA_TYPE,'
    + N' IS_DETERMINISTIC COLLATE DATABASE_DEFAULT AS IS_DETERMINISTIC,'
    + N' IS_IMPLICITLY_INVOCABLE COLLATE DATABASE_DEFAULT AS IS_IMPLICITLY_INVOCABLE,'
    + N' IS_NULL_CALL COLLATE DATABASE_DEFAULT AS IS_NULL_CALL,'
    + N' IS_USER_DEFINED_CAST COLLATE DATABASE_DEFAULT AS IS_USER_DEFINED_CAST, LAST_ALTERED,'
    + N' MAX_DYNAMIC_RESULT_SETS, NUMERIC_PRECISION, NUMERIC_PRECISION_RADIX, NUMERIC_SCALE,'
    + N' ROUTINE_BODY COLLATE DATABASE_DEFAULT AS ROUTINE_BODY,'
    + N' ROUTINE_CATALOG COLLATE DATABASE_DEFAULT AS ROUTINE_CATALOG,'
    + N' ''[REDACTED]'' AS ROUTINE_DEFINITION, ROUTINE_NAME COLLATE DATABASE_DEFAULT AS ROUTINE_NAME,'
    + N' ROUTINE_SCHEMA COLLATE DATABASE_DEFAULT AS ROUTINE_SCHEMA,'
    + N' ROUTINE_TYPE COLLATE DATABASE_DEFAULT AS ROUTINE_TYPE,'
    + N' SCHEMA_LEVEL_ROUTINE COLLATE DATABASE_DEFAULT AS SCHEMA_LEVEL_ROUTINE,'
    + N' SPECIFIC_CATALOG COLLATE DATABASE_DEFAULT AS SPECIFIC_CATALOG,'
    + N' SPECIFIC_NAME COLLATE DATABASE_DEFAULT AS SPECIFIC_NAME,'
    + N' SPECIFIC_SCHEMA COLLATE DATABASE_DEFAULT AS SPECIFIC_SCHEMA,'
    + N' SQL_DATA_ACCESS COLLATE DATABASE_DEFAULT AS SQL_DATA_ACCESS';
DECLARE @sql NVARCHAR(MAX) =
    N'SELECT DB_NAME() AS database_name, ' + @cols + N' FROM INFORMATION_SCHEMA.ROUTINES WHERE 1 = 0';

SELECT @sql = @sql + ISNULL((
        SELECT ' UNION ALL SELECT ' + QUOTENAME([name], '''') + ' AS database_name, ' + @cols
               + ' FROM ' + QUOTENAME([name]) + '.INFORMATION_SCHEMA.ROUTINES'
        FROM   sys.databases
        WHERE  state_desc = 'ONLINE'
               AND HAS_DBACCESS([name]) = 1
               AND [name] NOT IN ('master', 'tempdb', 'model', 'msdb')
        FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), '');

EXEC sys.sp_executesql @sql;
