name: acceptance

on:
  pull_request:
    types: [ opened, synchronize ]
  merge_group:
    types: [ checks_requested ]
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    environment: tool
    runs-on:
      group: larger-runners
      labels: larger
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.10'

      - name: Install hatch
        # see here for more details https://github.com/pypa/hatch/issues/2193
        run: pip install hatch==1.14.2 "virtualenv<21"

      - name: Install MSSQL ODBC Driver
        run: |
          chmod +x $GITHUB_WORKSPACE/.github/scripts/setup_mssql_odbc.sh
          $GITHUB_WORKSPACE/.github/scripts/setup_mssql_odbc.sh

      # TODO: Migrate tests to use Databricks clusters instead of Spark local mode
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd  # v4.0.0
        with:
          driver: docker-container

      - name: Build Spark Connect image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294  # v7.0.0
        with:
          context: .github/scripts/docker
          file: .github/scripts/docker/spark-connect.Dockerfile
          tags: lakebridge-spark-connect:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup Spark Connect
        run: .github/scripts/docker/setup_spark_remote.sh

      - name: Run integration tests
        uses: databrickslabs/sandbox/acceptance@acceptance/v0.4.4
        with:
          vault_uri: ${{ secrets.VAULT_URI }}
          directory: ${{ github.workspace }}
          timeout: 2h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TEST_ENV: 'ACCEPTANCE'
