name: Documentation Build

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'

permissions:
  contents: read

jobs:
  build:
    name: Build Docusaurus
    runs-on:
      group: databrickslabs-protected-runner-group
      labels: linux-ubuntu-latest
    permissions:
      # JFrog OIDC authentication.
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          sparse-checkout: |
            .github/actions
            docs
          sparse-checkout-cone-mode: 'true'

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 25.9.0
          cache: yarn
          cache-dependency-path: docs/lakebridge/yarn.lock

      - name: Setup for JFrog
        uses: ./.github/actions/jfrog-auth

      - name: Configure documentation environment
        run: make docs-dev

      - name: Build website
        run: make docs-build
